#!/bin/bash

set -e
set -o pipefail

NAME=the-tiniest-service

# If you're on Mac OS X, you'll need to `brew install coreutils` for sed to work correctly.
SED=$(which gsed || echo 'sed')

trap 'CODE=$?; if [[ -n "$CONTAINER" ]]; then docker stop "$CONTAINER"; fi; exit $CODE' 0

# 1. Build the image
docker build --tag="$NAME" .

# 2. Start up the container, record the container ID
CONTAINER="$(docker run -d -P "$NAME")"

# 3. Determine the docker host address
HOST="$($SED -r 's#tcp://([^:]+).*#\1#' <<< "${DOCKER_HOST:-localhost}")"

# 4. Determine the port of the container started in step 2
PORT="$(docker port "$CONTAINER" 8080 | $SED -r 's/.+://')"

# 5. Wait for the server to start
sleep 35

# 6. Ensure the container is available
curl --fail "$HOST:$PORT"
